### PR TITLE
Fix translation for zh_TW

### PR DESCRIPTION
**Pull request by sciuridae0603**
Correct words for Chinese(Taiwan) , and add missing translation.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@sciuridae0603 i am preparing a new version 3.5, which has a number of additional rules that will need translation. 

 I could send you the current version of this language file to you for translation if you are willing

**Comment by sciuridae0603** [comment]
@mikeerickson sure , i can translation it :)

**Comment by mikeerickson** [comment]
@sciuridae0603 I have sent it to you via email.  Thanks for your assitance.

**Comment by mikeerickson** [comment]
@sciuridae0603 The email address I used from your github profile returned undeliverable.  Which email address would you like me to send the file?

**Comment by sciuridae0603** [comment]
@mikeerickson umm... try admin@r20.tw instead.

**Comment by mikeerickson** [comment]
Hello @sciuridae0603 

i have tried again to send you via email, but again it was returned (I used the above email address)

I am not sure the reason for return (Policy reason)

```
<admin@r20.tw>: host spool.mail.gandi.net[217.70.178.1] said: 550 5.7.1  Reject
   for policy reason RULE1_1. See http://postmaster.gandi.net (in reply to end
   of DATA command)
Reporting-MTA: dns; gateway23.websitewelcome.com
X-Postfix-Queue-ID: EF44E21991
X-Postfix-Sender: rfc822; mike.erickson@codedungeon.io
Arrival-Date: Tue,  9 Mar 2021 19:33:55 -0600 (CST)

Final-Recipient: rfc822; admin@r20.tw
Original-Recipient: rfc822;admin@r20.tw
Action: failed
Status: 5.7.1
Remote-MTA: dns; spool.mail.gandi.net
Diagnostic-Code: smtp; 550 5.7.1  Reject for policy reason RULE1_1. See
   http://postmaster.gandi.net
```

If you happen to know the reason, please let me know and I will try again.

We are close to release 3.5, thus I would like to get this translation file into the final release.

**Comment by sciuridae0603** [comment]
Um...

Maybe you sent mail that contains zip file , and mail server don't accept
it , just upload it to google drive etc... , and send me link.

**Comment by mikeerickson** [comment]
> Um... Maybe you sent mail that contains zip file , and mail server don't accept it , just upload it to google drive etc... , and send me link.
> […](#)

It was not a zip file, just the raw `.js` file. I will arrange to get it on a drive tomorrow

**Comment by mikeerickson** [comment]
@sciuridae0603 OK, one more try!  I have placed the file on my Google Drive

https://drive.google.com/file/d/1WX47C_3u3EQnzkuf7PN95m20w8GxBl4_/view?usp=sharing

**Comment by sciuridae0603** [comment]
https://gist.github.com/sciuridae0603/d2808f5a9b1dca5bde5e4272c3d0d51c
Here you are!

**Comment by mikeerickson** [comment]
Hello @sdr0x07b6 

So, it seems I had not updated the existing zh_TW file with all the additional rules added in v3.5

Please see this gist which contains the "updated" zh_TW file to contain everything new.  When you have a moment, if you could add the translation, I would appreciate it.

https://gist.github.com/mikeerickson/6780ff8c0b918086acec84e78766bad2

**Comment by sdr0x07b6** [comment]
@mikeerickson 
Hello,
I was not involved in the translation of "zh_TW".
I was only involved in "ja".
I don't even know what language "zh_TW" is.

**Comment by mikeerickson** [comment]
@sciuridae0603 please see above 

@sdr0x07b6 my apologies, I tagged the wrong person 🤓

**Comment by sciuridae0603** [comment]
@mikeerickson Umm... I think i need explanation of new rules , can you give me exmaple or explanation of new rules?

**Pull request closed without merging**
